"""Added Users table

Revision ID: e859185a7f49
Revises: feb6a4a1ecf9
Create Date: 2022-01-21 22:38:00.364085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e859185a7f49'
down_revision = 'feb6a4a1ecf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
