"""Added Meet.join_code unique constraint

Revision ID: feb6a4a1ecf9
Revises: b01cb8850f0f
Create Date: 2022-01-21 22:19:48.879332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb6a4a1ecf9'
down_revision = 'b01cb8850f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meets_join_code', table_name='meets')
    op.create_index(op.f('ix_meets_join_code'), 'meets', ['join_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meets_join_code'), table_name='meets')
    op.create_index('ix_meets_join_code', 'meets', ['join_code'], unique=False)
    # ### end Alembic commands ###
